### ISSUE TITLE
Python test.api cannot establish new connectioon.

### ISSUE THREAD

**Issue by yashank09** [lukalabs/cakechat#14]

**Comment by rodart** [comment]
Hi! If you mean https://github.com/lukalabs/cakechat/blob/master/tools/test_api.py script than did you run cakechat model on localhost? You can run it doing this: https://github.com/lukalabs/cakechat#running-the-system

**Comment by yashank09** [comment]
Yes I did. Sorry for not providing details before.. But I trained the model, than ran python server, and I see  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
on command line. However using another terminal to send content as mentioned in the readme gives me errno 61; cannot establish new connection.
Sorry but I just got into python for AI and DL.

**Comment by yashank09** [comment]
Anything guys? Still getting the same issue..

**Comment by rodart** [comment]
If you run bin/cakechat_server.py without docker, than try to change host to 127.0.0.1: 
```python
app.run(host='0.0.0.0', port=8080) -> app.run(host='127.0.0.1', port=8080)
```

**Comment by yashank09** [comment]
Could you tell me how to run the cakechat server using docker? I am running the app using docker, but im giving a normal python command for the server in my command line. How do I run the server with docker included ?
Thanks!

**Comment by rodart** [comment]
For running Cakechat using docker please see our docs: https://github.com/lukalabs/cakechat#quick-start

**Comment by yashank09** [comment]
I followed the guide and did all the steps correctly. Once I train my model and serve the app however, I start getting the API error if I try to send any context to the host. So Docker is running my app properly, but im not able to send any context using for ex : python tools/test_api.py -f 127.0.0.1 -p 8080 \
    -c "Hi, Eddie, what's up?" \
Any clue ?

**Comment by rodart** [comment]
It seems that you have some problem with docker container access from your host, maybe some other process connected to 8080 port. 
Could you try to run ping command inside docker container? like ```sudo docker exec cakechat-dev python tools/test_api.py -f 127.0.0.1 -p 8080 -c "Hi, Eddie, what's up?"```

**Comment by yashank09** [comment]
Hey, I used the ping command on docker and I was successfully able to a response : 
{u'response': u"I'm just doing my work"}
So this means that docker and the port is working fine right ? So should I be using this command to test my bot ? Any ideas on how I can make the testing work as mentioned in the readme ? 
Thanks !

**Comment by rodart** [comment]
As I said before, It seems that you have some problem with docker container access from your host. If you got the response from the model that means cakechat works fine.
