### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [lukalabs/cakechat#20]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by rodart** [comment]
Hi Mirza! Sounds great, looking forward to your logo! Our landing page might give you a clue - https://cakechat.replika.ai/

**Comment by mirzazulfan** [comment]
Hi @rodart .. I've designed a logo for this awesome project. Tell me if you need some change or something else i'll fix it. 
![cc](https://user-images.githubusercontent.com/36124339/41399430-85064456-6fe4-11e8-909e-8d90b7cb0c5c.png)

**Comment by rodart** [comment]
Hi @mirzazulfan! Thank you for your work! We'll discuss the logo and let you know if we decide to use it.

**Comment by mirzazulfan** [comment]
Ok. If you need some change. Please let me know.
