### ISSUE TITLE
Training process gets killed.

### ISSUE THREAD

**Issue by vasiabratchuk** [lukalabs/cakechat#27]
Hi!
When running train.py the process always gets killed for some reason.
Could you please help with pointing out if I am doing anything wrong?
I have attached my terminal output.
[trainkilled.txt](https://github.com/lukalabs/cakechat/files/2284007/trainkilled.txt)

**Comment by vasiabratchuk** [comment]
Hi! I have tried playing around with the data I use, but the train.py still gets killed during epochs.
Maybe I'm not fully understanding what kind of data should be in certain files.
I have a correctly formatted corpus of data. 
1. Should the train_processed_dialogs.txt and val_processed_dialogs.txt contain the same dialog sets?
[train_processed_dialogs.txt](https://github.com/lukalabs/cakechat/files/2286871/train_processed_dialogs.txt)
[val_processed_dialogs.txt](https://github.com/lukalabs/cakechat/files/2286872/val_processed_dialogs.txt)

2. Here are the contents I have in the quality folder:
[context_free_questions.txt](https://github.com/lukalabs/cakechat/files/2286879/context_free_questions.txt)
[context_free_test_set.txt](https://github.com/lukalabs/cakechat/files/2286880/context_free_test_set.txt)
[context_free_validation_set.txt](https://github.com/lukalabs/cakechat/files/2286883/context_free_validation_set.txt)
I made the context_free_test_set.txt contain a sample of context free dialogs from the train_processed_dialogs.txt file. Then I made the context_free_questions.txt contain only the questions from the context_free_test_set.txt file.
What should be the contents of the context_free_validation_set.txt file?
At the moment I have made it to contain a sample of dialogs from the train_processed_dialogs.txt which are not in the context_free_test_set.txt file.
Could you please confirm if this is incorrect?
Unfortunately I could not get a proper understanding of what the exact functionality of val_processed_dialogs.txt and context_free_validation_set.txt files is.
Any help would be much appreciated.

**Comment by nicolas-ivanov** [comment]
@vasiabratchuk The format of your data seems to be correct. The amount of train data is too small to learn anything meaningful from scratch, consider enlarging your `train_processed_dialogs` dataset.

> Should the train_processed_dialogs.txt and val_processed_dialogs.txt contain the same dialog sets?

No, they should be different: train set is used for training your model and validation set for evaluating the performance of the trained model. These datasets should not intersect if you want to evaluate your model's performance correctly. The size of validation set can a 1k-10k examples, while train set typically has millions of examples. 

> What should be the contents of the context_free_validation_set.txt file?

The default contents of the files stored in `data/quality` folder is ok, you can leave them as is.

> Unfortunately I could not get a proper understanding of what the exact functionality of val_processed_dialogs.txt and context_free_validation_set.txt files is.

* `val_processed_dialogs.txt` – the samples are context sensitive, i.e. you need to provide samples with several consequent phrases to let your model understand the meaning of the context 
* `context_free_validation_set.txt` – the samples are context independent, i.e. you can feed only one phrase and it should be enough for a model to generate a meaningful answer

> When running train.py the process always gets killed for some reason.

What machine are you using for training? Most likely your OS runs out of memory and thus sends kill signal to stop the process.

**Comment by nicolas-ivanov** [comment]
@vasiabratchuk 
> Would you recommend using the cloud for training?

Yes, for sure.

**Comment by nicolas-ivanov** [comment]
I'm closing this issue now. Feel free to add more comments later.
