### ISSUE TITLE
Problem running the chat using Docker on Windows 10

### ISSUE THREAD

**Issue by eiriksvith** [lukalabs/cakechat#28]
Hi there, 

I have attempted to run CakeChat on my Windows 10 machine.

I've just followed the Quick Start guide and executed the following command:
docker run --name cakechat-dev -p 127.0.0.1:8080:8080 -it lukalabs/cakechat:latest \
    bash -c "python bin/cakechat_server.py"

The image is dowloaded just fine, but at the end Docker throws this error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"\\\\\": executable file not found in $PATH": unknown.

What could be the issue?

Thank you in advance.

**Comment by nicolas-ivanov** [comment]
@eiriksvith, hi!
Sorry for the delayed answer. Unfortunately we have a very limited possibility to test our docker container on Windows machines. I've tested it on Windows 10 Home edition with [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) and the server launched just fine. So, my suggestions for you are the following:
 
* Try running the container with Docker Toolbox as well and see if there are any problems.
* If something goes wrong consider installing Ubuntu distro either as a [Windows Subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or as a [standalone OS](https://www.ubuntu.com/download/desktop) and launching the container in it – in this case we'll be more capable to help you in case of troubles.

**Comment by nicolas-ivanov** [comment]
I'm closing this issue now. Feel free to reopen it, if you have more questions.
