### ISSUE TITLE
Adding "memory"

### ISSUE THREAD

**Issue by haxx0rman** [lukalabs/cakechat#32]
Is there a way to add a sort of memory to the AI? Remembering semantics like information about them or information about them. Similar to how Replika.ai remembers details.

If there is no built feature for this how could I go about creating it myself?

**Comment by nicolas-ivanov** [comment]
There is no easy way to add such feature to a generative dialog model. You can consider 

* [Memory Networks](https://blog.acolyer.org/2016/03/10/memory-networks/)
* [DSSM architecture](https://blog.statsbot.co/chatbots-machine-learning-e83698b1a91e)
* [Hand-crafted rules](https://dialogflow.com/)

**Comment by haxx0rman** [comment]
So if I wanted to add such a thing to cakechat I would have to create a layer of machine learning on top of cakechat to more so give the illusion of memory, yes?

**Comment by nicolas-ivanov** [comment]
I'm closing this issue now. Feel free to reopen it, if you have more questions.
