### ISSUE TITLE
How to start the model in continuous Q&A flow?

### ISSUE THREAD

**Issue by sanjanaargula** [lukalabs/cakechat#36]
Once we have tested the model using 

python tools/test_api.py -f 127.0.0.1 -p 8080 \
    -c "Hi, Eddie, what's up?" \
    -c "Not much, what about you?" \
    -c "Fine, thanks. Are you going to the movies tomorrow?"

how do we start up a session that works like an actual chatbot?  Like, immediate question and answers..?

**Comment by nicolas-ivanov** [comment]
@sanjanaargula the easiest way is to create a Telegram bot. Please see https://github.com/lukalabs/cakechat#telegram-bot

**Comment by sanjanaargula13** [comment]
Ya, even the telegram bot is giving me weird responses. But the thing is, I want to work it mainly on the command line.

**Comment by nicolas-ivanov** [comment]
> But the thing is, I want to work it mainly on the command line.

In this case you'll need to implement your own dialog loop. You may add it to [tools/test_api.api](https://github.com/lukalabs/cakechat/blob/master/tools/test_api.py) script, for example.

**Comment by sanjanaargula13** [comment]
How do i do that?
