### ISSUE TITLE
Server Not Found 

### ISSUE THREAD

**Issue by ananyachadha** [lukalabs/cakechat#39]
Hello!
Just getting started with cakechat, installing it without docker on macos.
worked perfectly up until I ran "python bin/cakechat_server.py"
It loaded the server, and said it was running, but when I visited the site it said 
"Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

Honestly, have no idea how to go about this -- would really appreciate your help :) 

Can't wait to get started messing around and building awesome stuff with CakeChat! I'll be sure to keep you updated with my project, hopefully, if I can get cakechat running properly. 

<img width="671" alt="screen shot 2019-01-15 at 12 47 11 pm" src="https://user-images.githubusercontent.com/34293728/51199070-d9023280-18c3-11e9-988a-11bf8aa1ec18.png">

**Comment by nicolas-ivanov** [comment]
Hello, @ananyachadha!
The provided url is not to visit but to send requests to. For example:

```
curl --header "Content-Type: application/json" --request POST --data '{"context":["hi!", "hi, how are you?", "good!"], "emotion":"joy"}' 'http://0.0.0.0:8060/cakechat_api/v1/actions/get_response'
```

The same request can be sent using the provided `tools/test_api.py` script:
```
python tools/test_api.py -f 0.0.0.0 -p 8060 -e "joy" \
    -c "hi!" \
    -c "hi, how are you?" \
    -c "good!"
```

See the corresponding section in our [Readme](https://github.com/lukalabs/cakechat#local-http-server). Hope this helps!

**Comment by ananyachadha** [comment]
Oh cool -- thought there was a front end for some reason. Thanks for your help! :)
