### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by SioKCronin** [lukalabs/cakechat#40]
Hi there!

I've followed the Quickstart instructions, yet am hitting an error I'm wondering if you have advice on:

``
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``

And on the server side
``
127.0.0.1 - - [18/Jan/2019 20:38:11] code 501, message Unsupported method ('POST')
``
``
127.0.0.1 - - [18/Jan/2019 20:38:11] "POST /cakechat_api/v1/actions/get_response HTTP/1.1" 501 -
``

I'm running Docker on Mac, which is working fine (help, ps, etc.). I'll keep exploring, but wanted to post this in case there's something obvious I can try. 

Thanks!

Sio

**Comment by nicolas-ivanov** [comment]
Hi @SioKCronin!
If you've found the answer to your question, please paste it here – may be helpful to others.
Thanks!

**Comment by SioKCronin** [comment]
Sure thing! It was super dumb. I misread the instructions that said "Run the CPU-only pre-built docker image & start the CakeChat serving the model on 8080 port", and closed my docker run tab and fired up a Pyton http.server that did, as might be expected, nothing. 

It's working fine now, and now I've learned a bit about Docker!

**Comment by nicolas-ivanov** [comment]
Got it, thanks!
