### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by SioKCronin** [lukalabs/cakechat#42]
I've downloaded and trained the model, but when I launch the server and try to call it in my browser I get a `This site can't be reached` error. I've tried `http://localhost:8080` and `http://127.0.0.1:8080/`.

I looked around and saw that I could use `docker inspect <CONTAINER-NAME>` which yielded an ip of `172.17.0.2`, which could also not be reached. 

Also, when I try the test conversation I get

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /cakechat_api/v1/actions/get_response (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103607eb8>: Failed to establish a new connection: [Errno 61] Connection refused',))
```
I found this [resource](https://forums.docker.com/t/connection-refused/45563/6) helpful, although I still don't know how I can access the Docker port mapping. 

I'm super psyched to get involved and help out with this project, even as a total bot beginner, so perhaps I can help build out a fuller "Absolute Beginner" doc to support such simple client-server debugging?

**Comment by nicolas-ivanov** [comment]
@SioKCronin please see the following answer: https://github.com/lukalabs/cakechat/issues/39#issuecomment-454501310

> so perhaps I can help build out a fuller "Absolute Beginner" doc to support such simple client-server debugging?

You are very welcome to create a pull request to enhance our [Readme](https://github.com/lukalabs/cakechat/blob/master/README.md) section!

**Comment by nicolas-ivanov** [comment]
Good!
