### ISSUE TITLE
Newbie Training our responses

### ISSUE THREAD

**Issue by hopeRespondent** [lukalabs/cakechat#45]
Hello, I would like to ask on how are we going to train the cakechat model. We used this as a group project on school and we have a very limited knowledge on programming. We asked helped on one of our professors and was able to run it but we have a big problem training it since he won't help us anymore. We already read your steps on training our own model and also some of the issues but we couldn't understand or maybe we were just overthinking the process. 
Our questions are : 
1. Where are we going to edit our responses?
2. How do we make the cakechat respond lwhat we want him to respond?
3. We've read that the corpus file is a JSON file can we edit this just on notepad? And does this file contains all our data responses or is it one response only in 5 different emotions?

This embarrassing but we know you have posted the answers but we can't understand. We ask specific questions because this so new to us. We hope you can help us :(

**Comment by nicolas-ivanov** [comment]
Hello @hopeRespondent 

> Where are we going to edit our responses?

All the train data should be placed in [train_processed_dialogs.txt](https://github.com/lukalabs/cakechat/blob/master/data/corpora_processed/train_processed_dialogs.txt). By default this file contains a dummy set of conversations (all the same) that should be replaced with your own data in the corresponding format. 

Please notice, that you need significant amount of data (at least several megabytes of text) if you want to train a new model from scratch or finetune a trained one. If trained on a small dataset the model will likely memorize your data, but won't be able to generalize to new unseen contexts.

> How do we make the cakechat respond lwhat we want him to respond?

As I wrote above, If trained on a small dataset the model will likely memorize your data, but won't be able to generalize to new unseen contexts.

> We've read that the corpus file is a JSON file can we edit this just on notepad?

Yes

> And does this file contains all our data responses or is it one response only in 5 different emotions?

It should contain all your data, each line corresponds to a separate conversation.

**Comment by hopeRespondent** [comment]
Thank you so much for your reply. I would like to apologize also for being too specific in asking questions. We are trying to train the data that we have but I guess this is too small to make the cakechat a trained one. For example, our trained lines were : 

[{"text": "Hi, [Name], what's up?", "condition": "joy"}, 
[{"text": " How was your day?", "condition": "joy"}, 

Are these lines okay? These are sample responses from us.
Can the cakechat identify the training data automatically and respond conversationally ? Or do we have to make a code on the program so that the cakechat will respond properly?

Again, I apologize. We honestly are too newbie in AI. I hope you understand.

**Comment by hopeRespondent** [comment]
Sir, another one is we already downloaded the download_model.py to run and to start our server to test the cakechat into our application. but as we have read that in order for us to train more data, it should be placed in train_processed_dialogs.txt but as we have cloned your repository and download all the requirements, the train_processed_dialogs.txt is not in our cloned project

Here is the project
![ai chat](https://user-images.githubusercontent.com/47651461/53016148-d7f68f00-3487-11e9-8cd1-0db82740454e.png)

inside of your cakechat > data > corpora_processed file it contains the train_processed_dialog.txt & val_processed_dialog but in our cloned project only look like this

![ai chat2](https://user-images.githubusercontent.com/47651461/53016302-44718e00-3488-11e9-81eb-a22ce809aa2e.png)

That is why also Sir we are confused on where we train our data.

**Comment by nicolas-ivanov** [comment]
> We are trying to train the data that we have but I guess this is too small to make the cakechat a trained one.

How much data do you have? In megabytes or number of samples.

> [{"text": "Hi, [Name], what's up?", "condition": "joy"},
> [{"text": " How was your day?", "condition": "joy"},
> 
> Are these lines okay?

I can see only contexts here, but not the responses. Something like this would be good:

```
[{"text": "Hi, <Name>, what's up?", "condition": "joy"},  "Hi, doing great!", "condition": "joy"}]
[{"text": " How was your day?", "condition": "joy"}, {"text": "Just amazing", "condition": "joy"}]
-- more samples here --
```
Note, that each line should be a valid json object, so I've replaced `[Name]` with `<Name>`. Also you should  understand that the model won't automatically cast a phrase "Hi, John, what's up?" to "Hi, <Name>, what's up?" – for a model these two contexts are relatively different. Our model wasn't trained on the samples with placeholders like the one that you suggest, so our model will likely not comprehend such a context correctly. If you want it to handle such cases, you need to finetune the pretrained model on a dataset that includes such examples (but not only them in order not to overfit your language model).

**Comment by nicolas-ivanov** [comment]
> That is why also Sir we are confused on where we train our data.

Your train data should replace the dummy dataset in the file `data/corpora_processed/train_processed_dialogs.txt`. If for some reason the file is not presented, just create it yourself )

**Comment by functioncall** [comment]
Hello, apologies for asking on a closed thread. I have one quick question. 

How long can be the context response list for one conversation example? Could the training file have different lengths of conversation examples as mentioned below? 

[{"text": "Hi, what's up?", "condition": "joy"},  "Hi, doing great!", "condition": "joy"}]
[{"text": "Hi, <Name>, what's up?", "condition": "joy"},  "Hi, doing great!", "condition": "joy"}, {"text": " How was your day?", "condition": "joy"}, {"text": "Just amazing", "condition": "joy"}]

Thanks!

**Comment by functioncall** [comment]
Actually those are two questions!

**Comment by nicolas-ivanov** [comment]
Hi, @functioncall!

> How long can be the context response list for one conversation example?

Each line should have at least two replicas – the first will be a context and the second will be an answer for this context. There is no max limit for the number of replicas.

> Could the training file have different lengths of conversation examples as mentioned below?

Yes, absolutely.

For example, your trainset example for param `INPUT_CONTEXT_SIZE = 2` will be transformed to the following set of training samples:

```
X: ["", "Hi, what's up?"], C: [<joy_id>] → Y: ["Hi, doing great!"]
X: ["Hi, <Name>, what's up?", "Hi, doing great!"], C: [<joy_id>] → Y: ["How was your day?"]
X: ["Hi, doing great!", "How was your day?"], C: [<joy_id>] → Y: ["Just amazing"]
```

Notice:

* The first line was transformed to one training sample with context X of length 2 where the first replica is just an empty line (after transforming tokens sequence to tokens ids it will be a sequence of `<pad>` token ids)
* The second line was unwrapped to two training samples, both having contexts of length 2. So, if you have a long sequence of consequent replicas, they will transformed to several training samples, depending on the value of `INPUT_CONTEXT_SIZE`.

**Comment by nicolas-ivanov** [comment]
@hopeRespondent, next time feel free to open a new issue – it's a better option, since your question doesn't not directly relate to the original question of this thread.

**Comment by functioncall** [comment]
> Notice:
> 
> * The first line was transformed to one training sample with context X of length 2 where the first replica is just an empty line (after transforming tokens sequence to tokens ids it will be a sequence of `<pad>` token ids)
Got it

> * The second line was unwrapped to two training samples, both having contexts of length 2. So, if you have a long sequence of consequent replicas, they will transformed to several training samples, depending on the value of `INPUT_CONTEXT_SIZE`.

So if my understanding is correct, for INPUT_CONTEXT_SIZE = 3, the training example should be transformed like this.

[ {"text": "Hi, what's up?", "condition": "joy"}, {"text": "Nothing much, how about you?", "condition": "joy"},  {"text": "Its been a great day actually.", "condition": "joy"}, {"text": "That's great! You should celebrate.", "condition": "joy"},  {"text": "Hmm, maybe that's not a bad idea.", "condition": "joy"}, {"text": "Your welcome!", "condition": "joy"},]

X: ["", "", "Hi, what's up?"], C: [joy] → Y: ["Nothing much, how about you?"]
X: ["", "Hi, what's up?", "Nothing much, how about you?"], C: [joy] → Y: ["Its been a great day actually."]
X: ["Hi, what's up?", "Nothing much, how about you?", "Its been a great day actually."], C: [joy] → Y: ["That's great! You should celebrate."]
X: ["Nothing much, how about you?", "Its been a great day actually.", "That's great! You should celebrate."], C: [joy] → Y: ["Hmm, maybe that's not a bad idea."]
X: [" It's been a great day actually", "That's great! You should celebrate.", "Hmm, maybe that's not a bad idea."], C: [joy] → Y: ["Your welcome!"]

**Comment by nicolas-ivanov** [comment]
Yes, your example seems to be correct. I had a mistake in mine – the second line is unwrapped to 3 train samples, not 2. Updated my comment above.

**Comment by functioncall** [comment]
Thank you for help!
