### ISSUE TITLE
no such option: --process-dependency-links

### ISSUE THREAD

**Issue by hurlenko** [lukalabs/cakechat#46]
`--process-dependency-links` got deprecated and is now removed from pip so docker build fails. See [here](https://github.com/pypa/pip/issues/3939).

**Comment by nicolas-ivanov** [comment]
@hurlenko that's right. For CakeChat the best solution for now is to use pip 18.1. You can ensure this by adding the corresponding line to the dockerfile: 
```bash
RUN pip3 --no-cache-dir install pip==18.1
RUN pip3 --no-cache-dir install -r /root/cakechat/requirements.txt --process-dependency-links
```

**Comment by mihaha** [comment]
Hi @hurlenko! 
Thank you for asking. I've fixed this in https://github.com/lukalabs/cakechat/pull/47
