### ISSUE TITLE
Amount of training data and training time

### ISSUE THREAD

**Issue by mnsotelo** [lukalabs/cakechat#49]
Hi, first I would like to say thank you for this amazing repository. 

I have 2 questions related with training the model:

What is the amount of data that you used to train your model? 

What are the specifications of the hardware that you used to train your model and how much time did it take to completely train?

Thank you very much and I apologize for my bad english.

**Comment by nicolas-ivanov** [comment]
Hi @mnsotelo!

>What is the amount of data that you used to train your model?

11Gb of twitter dialogs

> What are the specifications of the hardware that you used to train your model and how much time did it take to completely train?

Nvidia GeForce GTX 1080
approximately 1 week for 1 epoch

**Comment by mnsotelo** [comment]
May I ask also about the number of epochs you used to train the model?

**Comment by nicolas-ivanov** [comment]
Sure, 1 epoch.

**Comment by mnsotelo** [comment]
Thank you very much!
