### ISSUE TITLE
Using the trained model

### ISSUE THREAD

**Issue by HarshitSoni1903** [lukalabs/cakechat#50]
I have retrained the default model and trained it on a different data using the downloaded model weights as initial model weights(in Reverse Mode).
So now the question is how to use the model that i trained and not the one that was downloaded through the provided script download_model.py
Also, i wish to use colab environment and i am not sure how to use gpu, as i succesfully configured the libgpuarray but dont know where to put the gpu id or how to find it in colab. The most i could figure was, the gpu device name is "device:GPU:0" with similar steps given in(https://www.kdnuggets.com/2018/02/google-colab-free-gpu-tutorial-tensorflow-keras-pytorch.html/2)
i reached the utils/env.py file in cakechat and there a 'GPU-ID' was discovered but what value to supply is not clear.
It will be great if you could help me with that.

Thanks

**Comment by nicolas-ivanov** [comment]
Hi, @HarshitSoni1903 !

> So now the question is how to use the model that i trained and not the one that was downloaded through the provided script download_model.py

The trained models are stored at `<root of cakechag project>/data/nn_models`. Since the same folder is used by default for fetching our pretrained models from S3, if you didn't change any settings in config.py you most likely have overwritten the pretrained model with your newly trained one. That's ok, just make sure it's the case by taking a look at the modification time of the model's file. After that you can launch scripts like `python tools/generate_predictions.py` and the default location will be used to load model's weights, which are in your case the weights of your newly trained model.

If you want to load the model's weights from other location, pass `-m` flag to the script:

```
python tools/generate_predictions.py -m <full path to your models weights file>
```

**Comment by nicolas-ivanov** [comment]
> Also, i wish to use colab environment and i am not sure how to use gpu, as i succesfully configured the libgpuarray but dont know where to put the gpu id or how to find it in colab.

In Theano you need to specify GPU params id via environment variables and that exactly what [`init_theano_env()`](https://github.com/lukalabs/cakechat/blob/93cb30f698d285741a1378ff01d95cd16eb0ef85/cakechat/utils/env.py#L25) does. So you can explicitly change this line 

https://github.com/lukalabs/cakechat/blob/1efee48352caebfa4bda737c7e35de8edab89aab/tools/train.py#L10

to

```
init_theano_env(gpu_id='0')
```
in order run make GPU 0 visible to Theano. After that proceed running the code as you would on CPU.

**Comment by HarshitSoni1903** [comment]
Following the changes you specified i used initial model and tried training it on Nvidia GTX 1050Ti(4GB) with train size of 8.3 MB but a whole new error pops up:

[13.03.2019 19:36:28.119][INFO][2539][cakechat.dialog_model.model][410] Compiling train function...
Traceback (most recent call last):
  File "tools/train.py", line 107, in <module>
    train(init_path=args.init_weights, is_reverse_model=args.reverse)
  File "tools/train.py", line 81, in train
    train_model(nn_model)
  File "/root/cakechat/cakechat/dialog_model/train.py", line 250, in train_model
    loss = nn_model.train(*train_batch)
  File "/root/cakechat/cakechat/dialog_model/model.py", line 433, in train
    return self._train_fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 654, in pygpu.gpuarray.pygpu_empty (pygpu/gpuarray.c:9764)
  File "pygpu/gpuarray.pyx", line 280, in pygpu.gpuarray.array_empty (pygpu/gpuarray.c:5616)
pygpu.gpuarray.GpuArrayException: out of memory
Apply node that caused the error: GpuCrossentropySoftmaxArgmax1HotWithBias(GpuDot22.0, dense_output_probs.b, GpuReshape{1}.0)
Toposort index: 986
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(float32, (False,)), GpuArrayType<None>(int32, (False,))]
Inputs shapes: [(5952, 50000), (50000,), (5952,)]
Inputs strides: [(200000, 4), (4,), (4,)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [[GpuAdvancedSubtensor1(GpuCrossentropySoftmaxArgmax1HotWithBias.0, GpuContiguous.0)], [GpuCrossentropySoftmax1HotWithBiasDx(GpuAdvancedIncSubtensor1{inplace=True, set_instead_of_inc=False}.0, GpuCrossentropySoftmaxArgmax1HotWithBias.1, GpuReshape{1}.0)], []]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.


This appears right after step 1( perplexity 42.96). 

The only change to train.py:  device_id='0' as specified in previous comment. 
Os: Ubuntu 19.04
Environment: docker(as given in set-up instructions).

**Comment by nicolas-ivanov** [comment]
```
pygpu.gpuarray.GpuArrayException: out of memory
```
This line indicates that your GPU's memory isn't enough for the given experiment. Try reducing batch size in config file to a smaller value, for example 64:
https://github.com/lukalabs/cakechat/blob/d231b032a066a5aef4d4ffa227a9a52aa1ff1067/cakechat/config.py#L64

Also you may consider reducing the values of the following params: `INPUT_SEQUENCE_LENGTH`, `OUTPUT_SEQUENCE_LENGTH`, `MAX_PREDICTIONS_LENGTH`.
