### ISSUE TITLE
DialogFlow

### ISSUE THREAD

**Issue by rogsmith** [lukalabs/cakechat#68]
If you were to do this app today, would you have used DialogFlow?

**Comment by nicolas-ivanov** [comment]
@rogsmith these two approaches are quite different:

* DialogFlow - rules based approach, i.e. you need to manually define matching patterns and write answers for them. It implies a fair amount of manual labour, but gives you more control over result answers.
* CakeChat - generative neural dialog mode, i.e. you need to train it on a large dialog corpus, for example, Twitter logs and it figures out the rules of answers composition by itself. No manual labour is required (except the dataset preparation), however you have almost no control over the result answers, which sometimes may lead to meaningless or even offensive answers.

Rules-based and generative models (and also selective models) are not mutually exclusive, but rather complimentary approaches to building dialog systems.
