### ISSUE TITLE
APK?

### ISSUE THREAD

**Issue by Innomen** [lukalabs/cakechat#70]
I'd rather not install this through the Google play store, but I don't trust these various apk pages either. I guess technically the issue I'm reporting is the lack of an APK on the releases page.

Thanks for your patience.

**Comment by nicolas-ivanov** [comment]
@Innomen are you talking about a lightweight client application that could send requests to a server with the model? It is certainly doable but we don't plan to release such package in the near future.

**Comment by Innomen** [comment]
> @Innomen are you talking about a lightweight client application that could send requests to a server with the model? It is certainly doable but we don't plan to release such package in the near future.

Ts this not related to: 
https://play.google.com/store/apps/details?id=ai.replika.app
?

**Comment by nicolas-ivanov** [comment]
@Innomen, yes CakeChat is related to Replika, however it is just one of the number of models that are used in this application. In general Replika is way more advance in comparison to CakeChat and provide much smoother user experience. Since Replika uses several weighty deep learning models that are run on GPUs, it is currently technically impossible to fit it in a standalone APK.

**Comment by Innomen** [comment]
Ahh. Thank you for explaining. I wonder how many of the users of the playstore app realize they are talking "privately" to a server. X) Oh well, might as well close this.

**Comment by nicolas-ivanov** [comment]
No idea :) Anyway, all the messages are encrypted on the client side before they are sent to the server, as stated on Replika's help page:
https://help.replika.ai/hc/en-us/articles/360000885432-Is-my-conversation-with-Replika-encrypted-

**Comment by Innomen** [comment]
Well yea except that the people server side can read everything. Defeats the purpose as far as I'm concerned. I mean we're talking about a psychotherapy context here, zero privacy is an automatic no-go.
