### ISSUE TITLE
Recommended server specs?

### ISSUE THREAD

**Issue by sheldonrampton** [lukalabs/cakechat#71]
I've got cakechat running now on a Debian box that I set up on Google Cloud Platform and am using it on a test app receives messages and sends back response to a Facebook messenger app. It's nice!

I'm wondering if you have any suggestions regarding server requirements: recommended RAM, disk size, number of CPUs, etc.?

**Comment by nicolas-ivanov** [comment]
@sheldonrampton that depends on your demands, actually. What RPS are you expecting to have?

To max out the performance you should consider renting a GPU with CUDA support: https://developer.nvidia.com/cuda-gpus

The performance varies a lot for different generation modes. Here are the results we've got on Nvidia GeForce RTX 2080 when running the server with 4 workers on 1 GPU using [gunicorn](https://github.com/lukalabs/cakechat#gunicorn-http-server):
* 60 RPS for `PREDICTION_MODES = sampling`
* 3.6 RPS for `PREDICTION_MODES = sampling_reranking`
