### ISSUE TITLE
How to train data with new condition

### ISSUE THREAD

**Issue by sshuvro58** [lukalabs/cakechat#72]
Right now, it is only based on emotion, but I want to add one more parameter as an example topic 

`
[{"text": "Hi, Eddie, what's up?", "condition": "joy","topic": "introduction"}, {"text": "Not much, what about you?", "condition": "neutral","topic": "introduction"}, {"text": "Fine, thanks. Are you going to the movies tomorrow?", "condition": "neutral","topic": "introduction"}, {"text": "No, I've watched the new Star Wars already and it was just terrible!", "condition": "anger","topic": "introduction"}]`

How can I accomplish this?

**Comment by nicolas-ivanov** [comment]
@sshuvro58 At the moment CakeChat only supports one condition. So, option 1 is to use only topics conditions, in this case the train data will look like this:

```
[{"text": "Hi, Eddie, what's up?", "condition": "introduction"}, {"text": "Not much, what about you?", "condition": "introduction"}, {"text": "Fine, thanks. Are you going to the movies tomorrow?", "condition": "introduction"}, {"text": "No, I've watched the new Star Wars already and it was just terrible!", "condition": "introduction"}]
```

Option 2 is too merge two conditions in one string label, like this:

```
[{"text": "Hi, Eddie, what's up?", "condition": "joy_introduction"}, {"text": "Not much, what about you?", "condition": "neutral_introduction"}, {"text": "Fine, thanks. Are you going to the movies tomorrow?", "condition": "neutral_introduction"}, {"text": "No, I've watched the new Star Wars already and it was just terrible!", "condition": "anger_introduction"}]
```
