### ISSUE TITLE
Docker containers does not start on docker run

### ISSUE THREAD

**Issue by sr229** [lukalabs/cakechat#8]
Now in the context of using your Docker container in container platforms like OpenShift or in a orchestration platform like Kubernetes, this is a bit of a no-no.

I'm proposing to add another CMD layer that would be used by container platforms to tell the container to start instead of dropping to the shell, which would cause a back off in OpenShift/Kubernetes,

This is doable in CPU but GPU would need some special configuration, which makes it a bit unachievable at the moment.

**Comment by nsmetanin** [comment]
A copy of my response from PR:

Our dockerfiles are primarily made for development usage — i.e. you can start the container, attach to a shell inside of it, run some scripts (training, metrics, etc). Your change makes it very specific, suitable only for production deployment, so I think we can't accept it right now.

If you want to run it in your favorite environment, you'd better set the docker run command (like in https://github.com/lukalabs/cakechat/blob/master/README.md#quick-start) or write your own Dockerfile which includes our docker image by making use of FROM statement and build it.

So I'm closing the issue for now.
